/* =========================================================
   SMARTVISION (Oracle ????) - 6 TABLES + SEQUENCES + TRIGGERS
   + INDEX + REQUETES (recherche/tri)
   Tables: EMPLOYES, PROJETS, EQUIPEMENTS, ECHANTILLONS, EXPERIENCES, PUBLICATIONS
   ========================================================= */

------------------------------------------------------------
-- A) DROP (tables + sequences)
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PUBLICATIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EXPERIENCES  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ECHANTILLONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EQUIPEMENTS  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJETS      CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYES     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYES';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PROJETS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EQUIPEMENTS';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ECHANTILLONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EXPERIENCES';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PUBLICATIONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

------------------------------------------------------------
-- B) CREATE TABLES (???? IDENTITY)
------------------------------------------------------------

-- 1) EMPLOYES
CREATE TABLE EMPLOYES (
  EMPLOYE_ID     NUMBER PRIMARY KEY,
  CIN            VARCHAR2(20)  NOT NULL UNIQUE,
  NOM            VARCHAR2(80)  NOT NULL,
  PRENOM         VARCHAR2(80)  NOT NULL,
  ROLE           VARCHAR2(20)  NOT NULL,
  SPECIALISATION VARCHAR2(120),
  TEMPS_PLEIN    CHAR(1) DEFAULT 'O' NOT NULL,
  ACTIF          CHAR(1) DEFAULT 'O' NOT NULL,
  CONSTRAINT CK_EMP_ROLE CHECK (ROLE IN ('Chercheur','Technicien','Responsable')),
  CONSTRAINT CK_EMP_TP   CHECK (TEMPS_PLEIN IN ('O','N')),
  CONSTRAINT CK_EMP_ACT  CHECK (ACTIF IN ('O','N'))
);

-- 2) PROJETS
CREATE TABLE PROJETS (
  PROJET_ID               NUMBER PRIMARY KEY,
  NOM_PROJET              VARCHAR2(150) NOT NULL,
  DOMAINE_RECHERCHE       VARCHAR2(40)  NOT NULL,
  DATE_DEBUT              DATE,
  DATE_FIN                DATE,
  BUDGET                  NUMBER(14,3),
  STATUT                  VARCHAR2(20) DEFAULT 'En cours' NOT NULL,
  SOURCE_FINANCEMENT      VARCHAR2(150),
  NUM_APPROBATION_ETHIQUE VARCHAR2(60),
  NOMBRE_PUBLICATIONS     NUMBER DEFAULT 0 NOT NULL,
  RESPONSABLE_ID          NUMBER,
  CONSTRAINT CK_PRJ_DOM CHECK (
    DOMAINE_RECHERCHE IN ('G�nomique','Prot�omique','D�veloppement de m�dicaments','Biologie mol�culaire','Immunologie')
  ),
  CONSTRAINT CK_PRJ_STAT CHECK (STATUT IN ('En cours','Termin�','Suspendu','En attente')),
  CONSTRAINT CK_PRJ_BUD  CHECK (BUDGET IS NULL OR BUDGET >= 0),
  CONSTRAINT CK_PRJ_DATE CHECK (DATE_FIN IS NULL OR DATE_DEBUT IS NULL OR DATE_FIN >= DATE_DEBUT),
  CONSTRAINT FK_PRJ_RESP FOREIGN KEY (RESPONSABLE_ID) REFERENCES EMPLOYES(EMPLOYE_ID)
);

-- 3) EQUIPEMENTS
CREATE TABLE EQUIPEMENTS (
  EQUIPEMENT_ID              NUMBER PRIMARY KEY,
  NOM_EQUIPEMENT             VARCHAR2(120) NOT NULL,
  FABRICANT                  VARCHAR2(120),
  NUMERO_MODELE              VARCHAR2(80),
  DATE_ACHAT                 DATE,
  DATE_DERNIERE_MAINTENANCE  DATE,
  DATE_PROCHAINE_MAINTENANCE DATE,
  STATUT                     VARCHAR2(20) DEFAULT 'Actif' NOT NULL,
  LOCALISATION               VARCHAR2(120),
  DATE_LIMITE_CALIBRATION    DATE,
  RESPONSABLE_ID             NUMBER,
  CONSTRAINT CK_EQ_STAT CHECK (STATUT IN ('Actif','Hors service','Archiv�')),
  CONSTRAINT CK_EQ_MAINT CHECK (
    DATE_PROCHAINE_MAINTENANCE IS NULL OR DATE_DERNIERE_MAINTENANCE IS NULL
    OR DATE_PROCHAINE_MAINTENANCE >= DATE_DERNIERE_MAINTENANCE
  ),
  CONSTRAINT FK_EQ_RESP FOREIGN KEY (RESPONSABLE_ID) REFERENCES EMPLOYES(EMPLOYE_ID)
);

-- 4) ECHANTILLONS
CREATE TABLE ECHANTILLONS (
  ECHANTILLON_ID       NUMBER PRIMARY KEY,
  REFERENCE            VARCHAR2(80) NOT NULL UNIQUE,
  TYPE_ECHANTILLON     VARCHAR2(20) NOT NULL,
  SOURCE               VARCHAR2(120),
  DATE_COLLECTE        DATE,
  EMPLACEMENT_STOCKAGE VARCHAR2(200),
  TEMPERATURE_STOCKAGE VARCHAR2(20) NOT NULL,
  QUANTITE_RESTANTE    NUMBER(12,3),
  DATE_EXPIRATION      DATE,
  NIVEAU_DANGEROSITE   VARCHAR2(10) DEFAULT 'BSL-1' NOT NULL,
  CONSTRAINT CK_ECH_TYPE CHECK (TYPE_ECHANTILLON IN ('ADN','ARN','Prot�ine','Cellule','Tissu','Organisme')),
  CONSTRAINT CK_ECH_TEMP CHECK (TEMPERATURE_STOCKAGE IN ('-80C','-20C','+4C','Ambiante')),
  CONSTRAINT CK_ECH_BSL  CHECK (NIVEAU_DANGEROSITE IN ('BSL-1','BSL-2','BSL-3')),
  CONSTRAINT CK_ECH_QTE  CHECK (QUANTITE_RESTANTE IS NULL OR QUANTITE_RESTANTE >= 0)
);

-- 5) EXPERIENCES
CREATE TABLE EXPERIENCES (
  EXPERIENCE_ID  NUMBER PRIMARY KEY,
  TITRE          VARCHAR2(150) NOT NULL,
  PROTOCOLE      CLOB,
  HYPOTHESE      CLOB,
  DATE_DEBUT     DATE,
  DATE_FIN       DATE,
  STATUT         VARCHAR2(20) DEFAULT 'En cours' NOT NULL,
  CHERCHEUR_ID   NUMBER,
  PROJET_ID      NUMBER,
  EQUIPEMENT_ID  NUMBER,
  ECHANTILLON_ID NUMBER,
  CONSTRAINT CK_EXP_STAT CHECK (
    STATUT IN (
      'En cours',
      'Concluante',
      'Réussie','Échouée','Archivée',
      'Reussie','Echouee','Archivee',
      'R�ussie','�chou�e','Archiv�e'
    )
  ),
  CONSTRAINT CK_EXP_DATE CHECK (DATE_FIN IS NULL OR DATE_DEBUT IS NULL OR DATE_FIN >= DATE_DEBUT),
  CONSTRAINT FK_EXP_CH  FOREIGN KEY (CHERCHEUR_ID) REFERENCES EMPLOYES(EMPLOYE_ID),
  CONSTRAINT FK_EXP_PRJ FOREIGN KEY (PROJET_ID) REFERENCES PROJETS(PROJET_ID),
  CONSTRAINT FK_EXP_EQ  FOREIGN KEY (EQUIPEMENT_ID) REFERENCES EQUIPEMENTS(EQUIPEMENT_ID),
  CONSTRAINT FK_EXP_ECH FOREIGN KEY (ECHANTILLON_ID) REFERENCES ECHANTILLONS(ECHANTILLON_ID)
);

-- 6) PUBLICATIONS
CREATE TABLE PUBLICATIONS (
  PUBLICATION_ID NUMBER PRIMARY KEY,
  TITRE          VARCHAR2(250) NOT NULL,
  JOURNAL        VARCHAR2(150),
  ANNEE          NUMBER(4),
  DOI            VARCHAR2(120),
  STATUT         VARCHAR2(30) DEFAULT 'Soumise' NOT NULL,
  ABSTRACT       CLOB,
  IMPACT_FACTOR  NUMBER(6,3),
  CITATION_COUNT NUMBER DEFAULT 0 NOT NULL,
  AUTEUR_ID      NUMBER,
  PROJET_ID      NUMBER,
  CONSTRAINT CK_PUB_ANNEE CHECK (ANNEE IS NULL OR (ANNEE BETWEEN 1900 AND 2100)),
  CONSTRAINT CK_PUB_STAT  CHECK (STATUT IN ('Soumise','Accept�e','Publi�e','Rejet�e','Brouillon')),
  CONSTRAINT CK_PUB_CIT   CHECK (CITATION_COUNT >= 0),
  CONSTRAINT FK_PUB_AUT   FOREIGN KEY (AUTEUR_ID) REFERENCES EMPLOYES(EMPLOYE_ID),
  CONSTRAINT FK_PUB_PRJ   FOREIGN KEY (PROJET_ID) REFERENCES PROJETS(PROJET_ID)
);

------------------------------------------------------------
-- C) SEQUENCES + TRIGGERS (auto-increment)
------------------------------------------------------------
CREATE SEQUENCE SEQ_EMPLOYES     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROJETS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EQUIPEMENTS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ECHANTILLONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EXPERIENCES  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PUBLICATIONS START WITH 1 INCREMENT BY 1 NOCACHE;
/

CREATE OR REPLACE TRIGGER TRG_EMPLOYES_BI
BEFORE INSERT ON EMPLOYES
FOR EACH ROW
BEGIN
  IF :NEW.EMPLOYE_ID IS NULL THEN
    SELECT SEQ_EMPLOYES.NEXTVAL INTO :NEW.EMPLOYE_ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_PROJETS_BI
BEFORE INSERT ON PROJETS
FOR EACH ROW
BEGIN
  IF :NEW.PROJET_ID IS NULL THEN
    SELECT SEQ_PROJETS.NEXTVAL INTO :NEW.PROJET_ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_EQUIPEMENTS_BI
BEFORE INSERT ON EQUIPEMENTS
FOR EACH ROW
BEGIN
  IF :NEW.EQUIPEMENT_ID IS NULL THEN
    SELECT SEQ_EQUIPEMENTS.NEXTVAL INTO :NEW.EQUIPEMENT_ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_ECHANTILLONS_BI
BEFORE INSERT ON ECHANTILLONS
FOR EACH ROW
BEGIN
  IF :NEW.ECHANTILLON_ID IS NULL THEN
    SELECT SEQ_ECHANTILLONS.NEXTVAL INTO :NEW.ECHANTILLON_ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_EXPERIENCES_BI
BEFORE INSERT ON EXPERIENCES
FOR EACH ROW
BEGIN
  IF :NEW.EXPERIENCE_ID IS NULL THEN
    SELECT SEQ_EXPERIENCES.NEXTVAL INTO :NEW.EXPERIENCE_ID FROM DUAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_PUBLICATIONS_BI
BEFORE INSERT ON PUBLICATIONS
FOR EACH ROW
BEGIN
  IF :NEW.PUBLICATION_ID IS NULL THEN
    SELECT SEQ_PUBLICATIONS.NEXTVAL INTO :NEW.PUBLICATION_ID FROM DUAL;
  END IF;
END;
/

------------------------------------------------------------
-- D) INDEX
------------------------------------------------------------
CREATE INDEX IDX_EMP_CIN          ON EMPLOYES(CIN);
CREATE INDEX IDX_EMP_ROLE_TP      ON EMPLOYES(ROLE, TEMPS_PLEIN);

CREATE INDEX IDX_PUB_IMPACT       ON PUBLICATIONS(IMPACT_FACTOR);
CREATE INDEX IDX_PUB_ANNEE        ON PUBLICATIONS(ANNEE);

CREATE INDEX IDX_ECH_TYPE         ON ECHANTILLONS(TYPE_ECHANTILLON);
CREATE INDEX IDX_ECH_EXPIRATION   ON ECHANTILLONS(DATE_EXPIRATION);

CREATE INDEX IDX_EQ_FAB_NOM       ON EQUIPEMENTS(FABRICANT, NOM_EQUIPEMENT);
CREATE INDEX IDX_EQ_STAT_DATE     ON EQUIPEMENTS(STATUT, DATE_PROCHAINE_MAINTENANCE);

CREATE INDEX IDX_EXP_TITRE        ON EXPERIENCES(TITRE);
CREATE INDEX IDX_EXP_STAT_DATES   ON EXPERIENCES(STATUT, DATE_DEBUT, DATE_FIN);

CREATE INDEX IDX_PRJ_BUDGET_DATE  ON PROJETS(BUDGET, DATE_DEBUT, DATE_FIN);
CREATE INDEX IDX_PRJ_STATUT       ON PROJETS(STATUT);

------------------------------------------------------------
-- E) RECHERCHE + TRI (SQL Developer: DEFINE)
-- Run Script (F5)
------------------------------------------------------------

-- 1) EMPLOYES: CIN + tri role, temps plein
DEFINE p_cin = '';
SELECT EMPLOYE_ID, CIN, NOM, PRENOM, ROLE, TEMPS_PLEIN, ACTIF
FROM EMPLOYES
WHERE ('&p_cin' IS NULL OR '&p_cin' = '' OR CIN = '&p_cin')
ORDER BY ROLE, TEMPS_PLEIN DESC, NOM, PRENOM;

-- 2) PUBLICATIONS: mots-cl�s + tri impact factor
DEFINE p_kw = '';
SELECT PUBLICATION_ID, TITRE, JOURNAL, ANNEE, DOI, STATUT, IMPACT_FACTOR, CITATION_COUNT
FROM PUBLICATIONS
WHERE ('&p_kw' IS NULL OR '&p_kw' = ''
   OR LOWER(TITRE) LIKE '%' || LOWER('&p_kw') || '%'
   OR LOWER(DBMS_LOB.SUBSTR(ABSTRACT, 4000, 1)) LIKE '%' || LOWER('&p_kw') || '%')
ORDER BY NVL(IMPACT_FACTOR, -1) DESC, ANNEE DESC, TITRE;

-- 3) ECHANTILLONS: type + tri date expiration
DEFINE p_type = '';
SELECT ECHANTILLON_ID, REFERENCE, TYPE_ECHANTILLON, DATE_EXPIRATION, TEMPERATURE_STOCKAGE
FROM ECHANTILLONS
WHERE ('&p_type' IS NULL OR '&p_type' = '' OR TYPE_ECHANTILLON = '&p_type')
ORDER BY DATE_EXPIRATION ASC NULLS LAST;

-- 4) EQUIPEMENTS: fabricant + nom + tri statut/date
DEFINE p_fab = '';
DEFINE p_nom = '';
SELECT EQUIPEMENT_ID, NOM_EQUIPEMENT, FABRICANT, STATUT, DATE_PROCHAINE_MAINTENANCE
FROM EQUIPEMENTS
WHERE ('&p_fab' IS NULL OR '&p_fab' = '' OR LOWER(FABRICANT) LIKE '%'||LOWER('&p_fab')||'%')
  AND ('&p_nom' IS NULL OR '&p_nom' = '' OR LOWER(NOM_EQUIPEMENT) LIKE '%'||LOWER('&p_nom')||'%')
ORDER BY CASE STATUT WHEN 'Actif' THEN 1 WHEN 'Hors service' THEN 2 WHEN 'Archiv�' THEN 3 ELSE 9 END,
         DATE_PROCHAINE_MAINTENANCE ASC NULLS LAST,
         NOM_EQUIPEMENT;

-- 5) EXPERIENCES: titre + statut + tri dates
DEFINE p_titre = '';
DEFINE p_statut = '';
SELECT EXPERIENCE_ID, TITRE, STATUT, DATE_DEBUT, DATE_FIN
FROM EXPERIENCES
WHERE ('&p_titre' IS NULL OR '&p_titre' = '' OR LOWER(TITRE) LIKE '%'||LOWER('&p_titre')||'%')
  AND ('&p_statut' IS NULL OR '&p_statut' = '' OR STATUT = '&p_statut')
ORDER BY DATE_DEBUT DESC NULLS LAST, DATE_FIN DESC NULLS LAST;

------------------------------------------------------------
-- 5-bis) PATCH CONTRAINTE STATUT EXPERIENCES (DB EXISTANTE)
------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE EXPERIENCES DROP CONSTRAINT CK_EXP_STAT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

ALTER TABLE EXPERIENCES ADD CONSTRAINT CK_EXP_STAT CHECK (
  STATUT IN (
    'En cours',
    'Concluante',
    'Réussie','Échouée','Archivée',
    'Reussie','Echouee','Archivee',
    'R�ussie','�chou�e','Archiv�e'
  )
);

-- 6) PROJETS: recherche global + tri budget/date
DEFINE p_q = '';
SELECT PROJET_ID, NOM_PROJET, DOMAINE_RECHERCHE, STATUT, BUDGET, DATE_DEBUT, DATE_FIN
FROM PROJETS
WHERE ('&p_q' IS NULL OR '&p_q' = ''
   OR LOWER(NOM_PROJET) LIKE '%'||LOWER('&p_q')||'%'
   OR LOWER(DOMAINE_RECHERCHE) LIKE '%'||LOWER('&p_q')||'%'
   OR LOWER(STATUT) LIKE '%'||LOWER('&p_q')||'%'
   OR LOWER(SOURCE_FINANCEMENT) LIKE '%'||LOWER('&p_q')||'%'
   OR LOWER(NUM_APPROBATION_ETHIQUE) LIKE '%'||LOWER('&p_q')||'%')
ORDER BY NVL(BUDGET, -1) DESC, DATE_DEBUT DESC NULLS LAST, DATE_FIN DESC NULLS LAST, NOM_PROJET;

------------------------------------------------------------
-- F) COMPATIBILITE UI PUBLICATION (manuel, sans FK)
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PUBLICATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE PUBLICATION (
  id          NUMBER PRIMARY KEY,
  titre       VARCHAR2(300) NOT NULL,
  journal     VARCHAR2(200),
  annee       NUMBER(4),
  DOI         VARCHAR2(100) UNIQUE,
  status      VARCHAR2(50),
  abstract    CLOB,
  Id_projet   NUMBER,
  employee_id NUMBER
);